# https://www.gatsbyjs.org/docs/schema-customization/#foreign-key-fields
# https://www.gatsbyjs.org/docs/schema-customization/#extensions-and-directives

type ProjectStats implements Node {
  project: Projects @link
}

type Projects implements Node {
  stats: ProjectStats @link(by: "projectFullName", from: "fullName")
  mainContent: ProjectMainContent @link(by: "slug", from: "slug")
  projectTags: [ProjectTags] @link(by: "slug")
  ossCategory: OssCategory @link(by: "slug")
  subProjects: [Projects] @link(by: "slug")
  relatedProjects: [Projects] @link(by: "slug")
}