# https://www.gatsbyjs.org/docs/schema-customization/#foreign-key-fields

type ProjectStatsJson implements Node {
  project: ProjectsJson @link
}

type ProjectsJson implements Node {
  stats: ProjectStatsJson @link(by: "projectFullName", from: "fullName")
}