name: 'test-action'
description: 'Sync project and project-stats data'
inputs:
  github-token:
    description: 'Token to use for authentication to GitHub APIs'
    required: true
  projects:
    description: 'true/false - determines whether to fetch and sync the project data'
  project-stats:
    description: 'true/false - determines whether to fetch and sync the project-stats data'
runs:
  using: 'node16'
  main: 'src/index.js'
